### ISSUE TITLE
What should I install to get 3dmm?

### ISSUE THREAD

**Issue by szopeno** [clferrari/FacePartsSwap#2]
File "/home/XXX/FacePartsSwap/face_swap.py", line 10, in <module>
    from _3DMM import _3DMM
ModuleNotFoundError: No module named '_3DMM'

What should I install? Google search gives me several different results...

EDIT: Ah, I see. I need to copy _3DMM from https://github.com/clferrari/deep-3dmm-refinement

**Comment by clferrari** [comment]
My bad.. I did not push the _3DMM.py file. I will push it by tomorrow, in the meantime you can try using the one you find on our other repo. Thanks

**Comment by clferrari** [comment]
I have pushed the missing files, now it should work.

**Comment by szopeno** [comment]
If I may, what are the versions of the torch and keras? I am running into error communicates, which according to stackoverflow _may_ result from version conflicts. When I upgrade the one package, the error dissappears but another appears. I have Keras 2.6.0

E.g. "oduleNotFoundError: No module named 'keras.applications.resnet50'

When I upgrade keras to 2.10, I got "ImportError: cannot import name 'dtensor'"

Upgrading tensorflow via pip3 install --upgrde causes keras to be degraded back to 2.6.0

**Comment by clferrari** [comment]
I have torch 1.1.0 and tensorflow 1.13.1 installed in my environment, though tensorflow is not actually used. Where do you get that error?

**Comment by szopeno** [comment]
When i type "python3 main_c.py" . I am running it on CPU only.

python3 main_c.py 
2022-09-18 20:01:32.320531: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/lib64/mpi/gcc/openmpi3/:/usr/lib64/mpi/gcc/openmpi3/
2022-09-18 20:01:32.320656: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "main_c.py", line 3, in <module>
    from face_swap import face_swap
  File "/home/szopen/Pobrane/FacePartsSwap/face_swap.py", line 11, in <module>
    from evaluate import evaluate
  File "/home/szopen/Pobrane/FacePartsSwap/evaluate.py", line 13, in <module>
    from model import BiSeNet
  File "/home/szopen/Pobrane/FacePartsSwap/model.py", line 9, in <module>
    from resnet import Resnet18
  File "/home/szopen/.local/lib/python3.6/site-packages/resnet/__init__.py", line 1, in <module>
    from keras.applications.resnet50 import ResNet50
ModuleNotFoundError: No module named 'keras.applications.resnet50'

pip3 show torch:

Name: torch
Version: 1.10.1

pip3 show keras:
Name: keras
Version: 2.6.0

pip3 show resnet
Name: resnet
Version: 0.1

**Comment by clferrari** [comment]
Ok so maybe the problem is that when you do "from resnet import Resnet18" it seems that you are importing from the site-packages while the definition of Resnet18 is in the resnet.py file that is in the root folder of the project.

That file was missing when I first pushed the repo. Now it has been added maybe you can try pulling the repo and retry?

**Comment by szopeno** [comment]
Yup, that was that. There are now issues with other packages, but I will first try to solve that myself before reporting. Thank you!

**Comment by szopeno** [comment]
The simple case from running python3 main_c.py seems to work. I had to comment out the line 11 in file /home/szopen/Pobrane/FacePartsSwap/util_for_graphic.py

#from matplotlib.mlab import griddata

It seems it's not necessary as newer versions of matplotlib deprecated griddata, and the solution suggested by google is t use "from scipy.interpolate import griddata" which was already in line 5.
